### ISSUE TITLE
UnsatisfiedLinkError when jar included manually in project

### ISSUE THREAD

**Issue by DannyJo** [LabyMod/ultralight-java#9] opened 2020-09-03 18:52 UTC
Hello,

First of all I want to thank you for making these bindings for ultralight, I've been hoping someone would for a while, great work 👍 

Now to the issue, I downloaded the build artifacts from the actions workflow of the last build master at https://github.com/LabyMod/ultralight-java/actions/runs/223823217 and included the jar in my gradle project using `compile fileTree(include: ['*.jar'], dir: 'libs')`.

I then took some code from the lwjgl test module you have written and used that to try and load ultralight up.

```
  UltralightJava.extractNativeLibrary(nativesDir);
  UltralightJava.load(nativesDir);
```

I've double checked the path to the dll file which gets extracted and it's correct but either way an UnsatisfiedLinkError is thrown.

```
Caused by: java.lang.UnsatisfiedLinkError: ultralight-java-64 (JVMPORT015E Unable to resolve shared library references - a prerequisite shared library may be missing)
```

**Edit:**
It occurred to me that maybe I need the ultralight sdk dll files in my project so I added those, now it loads but throws another UnsatisfiedLinkError.

```
java.lang.UnsatisfiedLinkError: net/labymedia/ultralight/UltralightPlatform.instance()Lnet/labymedia/ultralight/UltralightPlatform;
```

This is thrown from this line:

```
platform = UltralightPlatform.instance();
```

Thanks

**Comment by Janrupf** [comment] 2020-09-04 15:55
Can't reproduce the issue on Windows 10 (version 2004, build 20201.1000) and on the included WSL2 system. I used the latest Ultralight SDK and the jars from the build you linked, worked every time. Sounds like you are not loading the native library at all (you certainly have at some point though?), which might cause the issue.

Can you show me your code?

(As a reference, here is my working test:
```java
package net.janrupf.ultralight.test;

import net.labymedia.ultralight.UltralightJava;
import net.labymedia.ultralight.UltralightLoadException;
import net.labymedia.ultralight.UltralightPlatform;

import java.nio.file.Path;
import java.nio.file.Paths;

public class TestMain {
  public static void main(String[] args) throws UltralightLoadException {
    Path runDir = Paths.get(".");
    UltralightJava.extractNativeLibrary(runDir);
    UltralightJava.load(runDir);

    UltralightPlatform platform = UltralightPlatform.instance();
    System.out.println(platform.getHandle());
  }
}
```
)

**Comment by DannyJo** [comment] 2020-09-04 18:53
It's clearly something environmental then.

I think it's got something to do with the placement of all the dll files. Where are your dll files placed?

I've now got a fresh project setup, using the same code you posted above and I get the below error.

My project folder contains the following dll files:

icudt63.dl
icuin63.dll
icuuc63.dll
Ultralight.dll
ultralight-java-64.dll
UltralightCore.dll
WebCore.dll

```
Unhandled exception
Type=Segmentation error vmState=0x00000000
Windows_ExceptionCode=c0000139 J9Generic_Signal=00000004 ExceptionAddress=00007FFF40B71F46 ContextFlags=0010004f
Handler1=00007FFED758EF90 Handler2=00007FFED9D7AB80
RDI=000002BF51F7D9C8 RSI=00007FFF40B8C6A0 RAX=0000000000000000 RBX=0000000000000001
RCX=0000000000800000 RDX=000000E4276FC5A0 R8=00007FFF40AFDD31 R9=000000E4276FC620
R10=000000E4276FC620 R11=000000E4276FC620 R12=0000000000000003 R13=0000000000000003
R14=00007FFEAD3FA101 R15=0000000000000003
RIP=00007FFF40B71F46 RSP=000000E4276FC870 RBP=000000E4276FCF10 GS=002B
FS=0053 ES=002B DS=002B
XMM0 0000000000000002 (f: 2.000000, d: 9.881313e-324)
XMM1 0000cfd3f4cc4152 (f: 4107026688.000000, d: 1.128986e-309)
XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM3 000000e42701d000 (f: 654430208.000000, d: 4.841384e-312)
XMM4 000002bf4d881764 (f: 1300764544.000000, d: 1.492406e-311)
XMM5 000000e4276fc321 (f: 661635904.000000, d: 4.841419e-312)
XMM6 0000000000114310 (f: 1131280.000000, d: 5.589266e-318)
XMM7 0064006e00690077 (f: 6881399.000000, d: 8.901042e-307)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=C:\Windows\SYSTEM32\ntdll.dll
Module_base_address=00007FFF40A70000 Offset_in_DLL=0000000000101f46
Target=2_90_20200715_679 (Windows 10 10.0 build 10240)
CPU=amd64 (24 logical CPUs) (0xffc77f000 RAM)
----------- Stack Backtrace -----------
```

It sounds like this is due to an entry point not being found.

**Comment by Janrupf** [comment] 2020-09-04 19:20
You seem to be missing a few other DLL's, here is the full list of what I have in the folder:
- **AppCore.dll** (not _really_ required, however, the current builds link against it, will get fixed in the future, required for now!)
- icudt63.dll
- icuin63.dll
- icuuc63.dll
- UltralightCore.dll
- Ultralight.dll
- ultralight-java-64.dll
- WebCore.dll

**Comment by DannyJo** [comment] 2020-09-04 19:26
Oh yes, I have AppCore.dll as well, sorry. 8 dll files in total.

I'm running adopt-openj9-11.0.8 JDK btw, not sure if that will matter.

**Comment by Janrupf** [comment] 2020-09-04 19:31
Oh, thats an interesting fact. Are you able to get any more information out of the error log? HotspotVM gives better error message, but maybe OpenJ9 is somehow incompatible with the binary builds?

**Comment by DannyJo** [comment] 2020-09-04 19:58
OK, so I ended up cloning ultralight and building it myself then copying the build dll files into my project and now it runs fine.

I also tried to download the latest release from ultralight github page and those dlls work fine. Looking at my downloads folder it would appear that I was originally using the 1.2.0 beta files which do not seem to work.

It's all good now, thanks for your help 👍

**Comment by Janrupf** [comment] 2020-09-04 20:12
OHHH, yeah, the latest Ultralight release does not work. ``ultralight-java`` required changes to be made in Ultralight, and those were done after the latest release. 

Glad it works now :+1:

**Closed by Janrupf** 2020-09-04 20:12 UTC
Labels: bug
